{% set name = "legendkit" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legendkit-{{ version }}.tar.gz
  sha256: 89c0d95c262420086f08c1fff06f9d3d3ee779cacf598464bec7bca10ac36853

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - matplotlib-base

test:
  imports:
    - legendkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Marsilea-viz/legendkit
  summary: Legend creation and manipulation with ease for matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
