{% set name = "legendkit" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/legendkit-{{ version }}.tar.gz
  sha256: cb4f4c11f678b2af25f037a675c1f21120f7d160efb6f52ce1378a1906ef159c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base

test:
  imports:
    - legendkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Marsilea-viz/legendkit
  summary: Legend creation and manipulation with ease for matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
